# select Environments
spring:
  profiles:
    active: local

# Local Env
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://capstone.c1p6fdr15njw.ap-northeast-2.rds.amazonaws.com:3306/alleat
    username: admin
    password: 12345678
    initialization-mode: always
    data: classpath:data.sql
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 10000
      connection-timeout: 30000
